In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
df = pd.read_csv("../data/ACCIDENTS_GU_BCN_2010.csv", encoding='latin=1') #el encoding es porque el dataset esta en catalan entonces le codificamos otro para los simbolos q no tenemos
df

,Número d'expedient,Codi districte,Nom districte,NK barri,Nom barri,Codi carrer,Nom carrer,Num postal caption,Descripció dia setmana,Dia de setmana,...,Hora de dia,Descripció torn,Descripció causa vianant,Número de morts,Número de lesionats lleus,Número de lesionats greus,Número de víctimes,Número de vehicles implicats,Coordenada UTM (Y),Coordenada UTM (X)
0,2010S003688,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,209900,Meridiana,0181 0181,Divendres,5,...,19,Tarda,Desconegut,0,0,0,0,1,"4584941,35","432017,96"
1,2010S007597,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,346402,Trinxant,0014 0014,Dilluns,1,...,11,Matí,Desconegut,0,1,0,1,2,"4585041,70","432014,69"
2,2010S001390,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,297001,Sant Antoni Maria Claret,0314 0316,Dijous,4,...,13,Matí,Desconegut,0,1,0,1,1,"4585117,42","431401,23"
3,2010S005416,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,134801,Freser,0007 0007,Dimarts,2,...,14,Tarda,Desconegut,0,1,0,1,2,"4584596,60","431397,75"
4,2010S008924,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,161407,Indústria,0258 0258,Divendres,5,...,14,Tarda,Desconegut,0,2,0,2,2,"4584932,86","431391,10"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9051,2010S004496,9,Sant Andreu,93-9-57,la Trinitat Vella,701267,Dalt (Besòs),001600000,Dimarts,2,...,7,Matí,Desconegut,0,1,0,1,2,"4588730,35","432614,40"
9052,2010S004253,9,Sant Andreu,92-9-60,Sant Andreu,176404,Llenguadoc,0110 0118,Divendres,5,...,8,Matí,Desconegut,0,1,0,1,2,"4586850,65","431894,29"
9053,2010S008126,9,Sant Andreu,92-9-60,Sant Andreu,296202,Gran de Sant Andreu,0113 0115,Dijous,4,...,23,Nit,Desconegut,0,1,0,1,2,"4586917,03","432269,90"
9054,2010S004114,9,Sant Andreu,93-9-59,el Bon Pastor,63850,Caracas,0026 0026,Dissabte,6,...,20,Tarda,Desconegut,0,2,0,2,2,"4588302,58","433411,20"
9055,2010S008469,9,Sant Andreu,93-9-58,Baró de Viver,701631,Pilar Miró,0004 0004,Dijous,4,...,14,Tarda,Desconegut,0,1,0,1,2,"4588789,93","433325,28"

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9056 entries, 0 to 9055
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Número d'expedient            9056 non-null   object
 1   Codi districte                9056 non-null   int64
 2   Nom districte                 9056 non-null   object
 3   NK barri                      9056 non-null   object
 4   Nom barri                     9056 non-null   object
 5   Codi carrer                   9056 non-null   int64
 6   Nom carrer                    9056 non-null   object
 7   Num postal caption            9056 non-null   object
 8   Descripció dia setmana        9056 non-null   object
 9   Dia de setmana                9056 non-null   int64
 10  Descripció tipus dia          9056 non-null   object
 11  NK Any                        9056 non-null   int64
 12  Mes de any                    9056 non-null   int64
 13  Nom mes                       9056 non-null   object
 14  Dia de mes                    9056 non-null   int64
 15  Hora de dia                   9056 non-null   int64
 16  Descripció torn               9056 non-null   object
 17  Descripció causa vianant      9056 non-null   object
 18  Número de morts               9056 non-null   int64
 19  Número de lesionats lleus     9056 non-null   int64
 20  Número de lesionats greus     9056 non-null   int64
 21  Número de víctimes            9056 non-null   int64
 22  Número de vehicles implicats  9056 non-null   int64
 23  Coordenada UTM (Y)            9056 non-null   object
 24  Coordenada UTM (X)            9056 non-null   object
dtypes: int64(12), object(13)
memory usage: 1.7+ MB

In [4]:
df["Date"] = df[u"Dia de mes"].apply(lambda x: str(x)) + "-" + df[u"Mes de any"].apply(lambda x: str(x)) + "-2010"

In [5]:
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")
df.sample(6)

,Número d'expedient,Codi districte,Nom districte,NK barri,Nom barri,Codi carrer,Nom carrer,Num postal caption,Descripció dia setmana,Dia de setmana,...,Descripció torn,Descripció causa vianant,Número de morts,Número de lesionats lleus,Número de lesionats greus,Número de víctimes,Número de vehicles implicats,Coordenada UTM (Y),Coordenada UTM (X),Date
1839,2010S005423,2,Eixample,23-2-8,l'Antiga Esquerra de l'Eixample,169409,Corts Catalanes,0533 0533,Dimarts,2,...,Tarda,Desconegut,0,1,0,1,2,"4581598,51","429688,15",2010-08-03
8731,2010S000608,2,Eixample,26-2-5,el Fort Pienc,169409,Corts Catalanes,0830X0830X,Dimarts,2,...,Tarda,Desconegut,0,0,0,0,1,"4583698,44","431911,01",2010-01-26
1672,2010S005882,9,Sant Andreu,92-9-60,Sant Andreu,209900,Meridiana,0612 0612,Dimarts,2,...,Tarda,Desconegut,0,2,0,2,2,"4588462,46","432129,16",2010-08-31
4025,2010S001181,10,Sant Martí,104-10-69,Diagonal Mar i el Front Marítim del Poblenou,143609,Josep Pla,0065 0065,Dimecres,3,...,Matí,Desconegut,0,1,0,1,2,"4584744,07","434138,94",2010-02-17
6377,2010S009038,2,Eixample,24-2-7,la Dreta de l'Eixample,18505,Aragó,0319 0319,Dijous,4,...,Tarda,Desconegut,0,1,0,1,2,"4583063,72","430603,70",2010-12-30
6881,2010S007350,10,Sant Martí,105-10-66,el Parc i la Llacuna del Poblenou,11200,Almogàvers,0211 0211,Dijous,4,...,Tarda,Desconegut,0,1,0,1,2,"4583678,55","432814,07",2010-10-28

In [6]:
accidents_2010 = df.groupby(["Date"]).size()
accidents_2010

Date
2010-01-01     7
2010-01-02    14
2010-01-03    15
2010-01-04    23
2010-01-05    31
              ..
2010-12-27    20
2010-12-28    21
2010-12-29    17
2010-12-30    19
2010-12-31    21
Length: 365, dtype: int64

In [7]:
print("accidents 2010:", accidents_2010.mean())

accidents 2010: 24.81095890410959

In [8]:
df_2013 = pd.read_csv("../data/ACCIDENTS_GU_BCN_2013.csv", encoding='latin=1') #el encoding es porque el dataset esta en catalan entonces le codificamos otro para los simbolos q no tenemos
df_2013

,Número d'expedient,Codi districte,Nom districte,NK barri,Nom barri,Codi carrer,Nom carrer,Num postal caption,Descripció dia setmana,Dia de setmana,...,Hora de dia,Descripció torn,Descripció causa vianant,Número de morts,Número de lesionats lleus,Número de lesionats greus,Número de víctimes,Número de vehicles implicats,Coordenada UTM (Y),Coordenada UTM (X)
0,2013S007360,-1,Desconegut,-1--1--1,Desconegut,-1,Desconegut,Desconegut,Dimecres,3,...,21,Tarda,Desconegut,0,1,0,1,2,-1,-1
1,2013S007723,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,152600,Guinardó,0028 0032,Dimarts,2,...,21,Tarda,Desconegut,0,1,0,1,2,"4585218,67","431621,41"
2,2013S005373,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,134801,Freser,0053 0053,Dimarts,2,...,10,Matí,Creuar per fora pas de vianants,0,1,0,1,1,"4585049,89","431605,09"
3,2013S001486,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,161407,Indústria,0224 0224,Dimarts,2,...,10,Matí,Altres,0,1,0,1,1,"4584836,20","431302,26"
4,2013S008254,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,161101,Independència,0357 0357,Dilluns,1,...,16,Tarda,Desconegut,0,1,0,1,2,"4584704,26","431385,76"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9452,2013S008023,9,Sant Andreu,93-9-59,el Bon Pastor,701265,Litoral (Besòs),000120000,Diumenge,7,...,18,Tarda,Desconegut,0,1,0,1,1,"4588266,09","433713,00"
9453,2013S006294,9,Sant Andreu,93-9-59,el Bon Pastor,701265,Litoral (Besòs),000140000,Dijous,4,...,17,Tarda,Desconegut,0,2,0,2,3,"4588083,71","433798,37"
9454,2013S005884,9,Sant Andreu,93-9-59,el Bon Pastor,701266,Litoral (Llobregat),000110000,Dimecres,3,...,10,Matí,Desconegut,0,9,0,9,2,"4588339,80","433640,52"
9455,2013S001311,9,Sant Andreu,93-9-59,el Bon Pastor,63850,Caracas,0050B0050B,Dimecres,3,...,17,Tarda,Desconegut,0,1,0,1,2,"4588592,95","433353,63"
9456,2013S006739,9,Sant Andreu,93-9-59,el Bon Pastor,123306,Ferran Junoy,0054 0054,Dilluns,1,...,10,Matí,Desconegut,0,2,0,2,2,"4588179,93","432914,61"

In [9]:
df_2013["Date"] = df_2013[u"Dia de mes"].apply(lambda x: str(x)) + "-" + df_2013[u"Mes de any"].apply(lambda x: str(x)) + "-2013"

In [10]:
df_2013["Date"] = pd.to_datetime(df_2013["Date"], format="%d-%m-%Y")
df_2013.sample(6)

,Número d'expedient,Codi districte,Nom districte,NK barri,Nom barri,Codi carrer,Nom carrer,Num postal caption,Descripció dia setmana,Dia de setmana,...,Descripció torn,Descripció causa vianant,Número de morts,Número de lesionats lleus,Número de lesionats greus,Número de víctimes,Número de vehicles implicats,Coordenada UTM (Y),Coordenada UTM (X),Date
4308,2013S004406,2,Eixample,26-2-5,el Fort Pienc,178308,Lepant,0143 0145,Dilluns,1,...,Matí,Desconegut,0,1,0,1,2,"4583305,39","431825,50",2013-06-17
966,2013S003079,6,Gràcia,61-6-28,Vallcarca i els Penitents,701267,Dalt (Besòs),000980000,Diumenge,7,...,Tarda,Desconegut,0,1,1,2,1,"4585501,14","428036,03",2013-04-28
951,2013S007633,5,Sarrià-Sant Gervasi,53-5-25,Sant Gervasi - la Bonanova,162909,Iradier,0023U0023U,Dissabte,6,...,Matí,Desconegut,0,1,0,1,2,"4584151,95","426797,91",2013-10-26
1392,2013S000712,3,Sants-Montjuïc,32-3-13,la Marina de Port,169409,Corts Catalanes,0128 0132,Dimarts,2,...,Tarda,Desconegut,0,2,0,2,2,"4579512,76","427654,60",2013-01-29
1013,2013S007702,7,Horta-Guinardó,74-7-33,el Baix Guinardó,73900,Castillejos,0397 0397,Dimarts,2,...,Matí,Desconegut,0,3,0,3,2,"4584859,91","430675,21",2013-10-29
8204,2013S009365,10,Sant Martí,101-10-64,el Camp de l'Arpa del Clot,289105,Rosselló,0536 0536,Dimecres,3,...,Matí,Desconegut,0,1,0,1,2,"4584674,21","431537,53",2013-12-25

In [11]:
accidents_2013 = df_2013.groupby(["Date"]).size()
accidents_2013

Date
2013-01-01    16
2013-01-02    18
2013-01-03    17
2013-01-04    29
2013-01-05    17
              ..
2013-12-27    21
2013-12-28    12
2013-12-29    13
2013-12-30    26
2013-12-31    19
Length: 365, dtype: int64

In [12]:
print("accidents 2013:", accidents_2013.mean())

accidents 2013: 25.90958904109589

In [13]:
accidents_df1 = accidents_2010.to_frame()
rows = np.random.choice(accidents_df1.index.values,200)
sample_df = accidents_df1.loc[rows]
est_std = sample_df.std()
print("Estimado de la desvacion estadar: ", est_std)
est_mean = sample_df.mean()
print("Estimado de la media: ", est_mean)

Estimado de la desvacion estadar:  0    8.302689
dtype: float64
Estimado de la media:  0    24.505
dtype: float64

In [14]:
mean_2010 = accidents_2010.mean()
std_2010 = accidents_2010.std()
n_2010 = len(accidents_2010)
IC=[mean_2010 - std_2010 *1.96/np.sqrt(n), mean_2010 + std_2010 *1.96/np.sqrt(n)]
print("IC:", IC)

NameError: name 'n' is not defined

In [18]:
mean_2013 = accidents_2013.mean()
std_2013 = accidents_2013.std()
n_2013 = len(accidents_2013)
IC=[mean_2013 - std_2013 *1.96/np.sqrt(n), mean_2013 + std_2013 *1.96/np.sqrt(n)]
print("IC:", IC)

IC: [np.float64(24.975156065800284), np.float64(26.8440220163915)]

In [21]:
#nivel de significancia alfa=0.05 (5%)
z_score= (mean_2013-mean_2010)/(np.sqrt((std_2010/n_2010)+(std_2013/n_2013)))
print(z_score)

4.993572550110768

Para el valor de significancia de 0,05 los valores criticos son +/- 1.96

In [16]:
#primera prueba de hipotesis

#una fabrica produce 150 unidades/hora con una desviacion estandar de 8 unidades, una maquina nueva produce 160 unidades/ hora con una desviaciom estandar de 8, total de muestras n=35
#nivel de significancia lo establecemos en alfa = 0.01 (2,576) porque la maquina es cara y queremos ser cautos

z_score1= (160-150)/(8/np.sqrt(35))
print (z_score1)
p_value1 =2*(1-stats.norm.cdf(abs(z_score1)))
print(p_value1)

7.395099728874521
1.412203687323199e-13